# Generated by Django 4.1.7 on 2023-03-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_pocketmoney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pocketmoney',
            name='email',
        ),
        migrations.AddField(
            model_name='pocketmoney',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
