# Generated by Django 4.1.7 on 2023-03-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_pocketmoney_email_pocketmoney_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocketmoney',
            name='user',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
