# Generated by Django 4.1.7 on 2023-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_pocketmoney_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('expense', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
