# Generated by Django 4.1.7 on 2023-03-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.CharField(default='August', max_length=30),
        ),
    ]
